-- 2024.03.28 ~ 2024.03.29 토이프로젝트 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER contact_toyProject IDENTIFIED BY contact_toyProject;

GRANT RESOURCE, CONNECT TO contact_toyProject;

ALTER USER contact_toyProject DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-----------------------------------------------------------------------------------------------
CREATE TABLE TB_MEMBER (
    MEMBER_NO NUMBER CONSTRAINT PK_MEMBER PRIMARY KEY,
    MEMBER_EMAIL VARCHAR2(100) NOT NULL,
    MEMBER_PW VARCHAR2(100) NOT NULL,
    MEMBER_NAME VARCHAR2(20) NOT NULL,
    MEMBER_PHONE CHAR(13) UNIQUE NOT NULL,
    MEMBER_DATE DATE DEFAULT SYSDATE NOT NULL,
    MEMBER_DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    UNIQUE(MEMBER_EMAIL),
    CHECK(MEMBER_DEL_YN IN('N','Y'))
);

COMMENT ON COLUMN TB_MEMBER.MEMBER_NO IS '회원번호(시퀀스)';
COMMENT ON COLUMN TB_MEMBER.MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN TB_MEMBER.MEMBER_NAME IS '회원 이름';
COMMENT ON COLUMN TB_MEMBER.MEMBER_PHONE IS '회원 연락처';
COMMENT ON COLUMN TB_MEMBER.MEMBER_DATE IS '가입일';
COMMENT ON COLUMN TB_MEMBER.MEMBER_DEL_YN IS '탈퇴여부';


CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE;


-- 샘플 계정1
INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user01@kh.com', 'pass01', '회원일'
, '010-1111-1111', DEFAULT, DEFAULT);

-- 샘플 계정2
INSERT INTO TB_MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'user02@kh.com', 'pass02', '회원이'
, '010-2222-2222', DEFAULT, DEFAULT);



CREATE TABLE TB_CONTACT (
    CT_NO NUMBER CONSTRAINT PK_CONTACT PRIMARY KEY,
    CT_NAME VARCHAR2(20) NOT NULL,
    CT_INFO VARCHAR2(500) NOT NULL,
    CT_DATE DATE DEFAULT SYSDATE NOT NULL,
    CT_DEL_YN CHAR(1) DEFAULT 'N' NOT NULL,
    MEMBER_NO NUMBER CONSTRAINT FK_MEMBER_NO REFERENCES TB_MEMBER NOT NULL
);

COMMENT ON COLUMN TB_CONTACT.CT_NO IS '연락처 번호(시퀀스)';
COMMENT ON COLUMN TB_CONTACT.CT_NAME IS '연락처 이름';
COMMENT ON COLUMN TB_CONTACT.CT_INFO IS '연락처 정보';
COMMENT ON COLUMN TB_CONTACT.CT_DATE IS '연락처 생성일';
COMMENT ON COLUMN TB_CONTACT.CT_DEL_YN IS '연락처 삭제여부';
COMMENT ON COLUMN TB_CONTACT.MEMBER_NO IS '작성자 회원 번호';

CREATE SEQUENCE SEQ_CONTACT_NO NOCACHE;

-- 연락처 샘플 1
INSERT INTO TB_CONTACT
VALUES(SEQ_CONTACT_NO.NEXTVAL, '홍길동', '학원 동기', DEFAULT, DEFAULT, 1);

INSERT INTO TB_CONTACT
VALUES(SEQ_CONTACT_NO.NEXTVAL, '나최고', '직장 동료', DEFAULT, DEFAULT, 1);


-- 누락된 폰 컬럼 추가
ALTER TABLE TB_CONTACT ADD(CT_PHONE CHAR(13));
ALTER TABLE TB_CONTACT MODIFY CT_PHONE NOT NULL;
UPDATE TB_CONTACT SET CT_PHONE = '010-1111-1234' WHERE CT_NO = 1;
UPDATE TB_CONTACT SET CT_PHONE = '010-2222-1234' WHERE CT_NO = 2;

-- 즐겨찾기 컬럼 추가
ALTER TABLE TB_CONTACT ADD(STAR CHAR(1) DEFAULT 'N');


COMMIT;


SELECT * FROM TB_MEMBER;
SELECT * FROM TB_CONTACT;


